### PR TITLE
Improve documentation and examples of hexfloats

### LINKED ISSUE #33: Hexfloats in documentation
Give better/additional examples, and rationale for the use of hex floats.

### PR DESCRIPTION
**Pull request by mborland**
Closes: #33

### CODE REVIEW

**Comment by mborland** [comment]
@NAThompson On the ML someone asked to improve the documentation and examples for hexfloats. Is there anything else you think should be covered?

**Comment by NAThompson** [comment]
@mborland : Nice writeup. One thing I have gotten stung by in the past (foolishly, of course) is that despite every float having a unique representation as a hexfloat, not every hexfloat corresponds to a unique float. This is because the number of bits in the significant of float32 and float64 is not divisible by 4.

**Comment by mborland** [comment]
> ... is that despite every float having a unique representation as a hexfloat, not every hexfloat corresponds to a unique float. This is because the number of bits in the significant of float32 and float64 is not divisible by 4.

I added that as a note because you could theoretically try to roundtrip binary to hex and back. Thanks.

**Comment by NAThompson** [comment]
> I added that as a note because you could theoretically try to roundtrip binary to hex and back.

Yeah . . . that's what I was trying when I learned about it!

**Pull request merged**
