### PR TITLE
Float to chars

### PR DESCRIPTION
**Pull request by mborland**

### CODE REVIEW

**Comment by mborland** [comment]
@pdimov I replaced the anonymous namespaces by templating the structs as you commented. Do you know of a workaround for the following error:

```
./boost/charconv/detail/floff.hpp:1504:49: error: cannot initialize aggregate of type 'const cache_entry_type [619] {aka const boost::charconv::detail::uint128 [619]}' with a compound literal
         {0xf70867153aa2db38, 0xb8cbee4fc66d1ea8}};
```

This only arises on GCC 4.8 and 4.9.

**Comment by pdimov** [comment]
I don't, sorry. It's probably because `uint128` is not an aggregate, but has a constructor. Why is GCC 4.x confused by that, I don't know.

**Comment by jk-jeon** [comment]
> I don't, sorry. It's probably because `uint128` is not an aggregate, but has a constructor. Why is GCC 4.x confused by that, I don't know.

I guess maybe we can just remove the constructor and make it into an aggregate? Will that fixes the issue?

In Dragonbox/floff projects, that the corresponding struct has a constructor is more or less just a historical artifact, 'cause initially it had only one member if the compiler supports native 128-bit integers. I removed that and just made it to always hold a pair of 64-bits because native 128-bit integers didn't seem to produce good assemblies.

**Comment by mborland** [comment]
> 
> I guess maybe we can just remove the constructor and make it into an aggregate? Will that fixes the issue?
> 

That seems to do it. Thanks.

**Comment by mborland** [comment]
@pdimov Do you have any further comments on this one? I addressed all of your existing comments along the way.

**Comment by pdimov** [comment]
`BOOST_CHARCONV_SAFEBUFFERS` is defined twice.

Check your uses of `_MSC_VER`. It means "MSVC and compatible compilers", but most of the current uses seem to only apply to MSVC. Use `BOOST_MSVC` if you mean "MSVC".

**Comment by pdimov** [comment]
> Scientific format will be of the form `+1.3e+3`.

Does scientific include the plus sign for positive numbers?

**Comment by mborland** [comment]
> > Scientific format will be of the form `+1.3e+3`.
> 
> Does scientific include the plus sign for positive numbers?

It does not, and I was also missing the fact that in scientific format the exponent will have a minimum of 2 digits. Correctly represented is: `1.3e+03`.

**Pull request merged**
