### PR TITLE
Remove use of <string> header

### PR DESCRIPTION
**Pull request by mborland**
Use std::strtol and std::strtoll for integer types to avoid bringing in string.

### CODE REVIEW

**Comment by pdimov** [comment]
Note that the use of `std::string` was a stub, merely to make the test pass. In our real implementation we can't use `strtol` because it's locale-dependent, and `from_chars` is locale-independent.

**Comment by mborland** [comment]
> Note that the use of `std::string` was a stub, merely to make the test pass. In our real implementation we can't use `strtol` because it's locale-dependent, and `from_chars` is locale-independent.

The parsers will be [locale dependent](https://en.cppreference.com/w/cpp/utility/from_chars). It'll require pre-processing if not in the standard "C" locale

**Comment by pdimov** [comment]
I don't understand. The specification of `from_chars` requires independence. Are you saying you won't implement that?

**Comment by mborland** [comment]
from_chars_result from_chars(const char* first, const char* last, integer-type & value, int base = 10);

1. Preconditions: base has a value between 2 and 36 (inclusive).

2. Effects: The pattern is the expected form of the subject sequence in the "C" locale for the given nonzero base, as described for strtol, except that no "0x" or "0X" prefix shall appear if the value of base is 16, and except that ’-’ is the only sign that may appear, and only if value has a signed type.

3. Throws: Nothing.

I am saying that the parser itself requires a "C" locale so we would need to pre-process. I am not saying the user needs to do this.

**Comment by pdimov** [comment]
Preprocess? We just need to parse it ourselves without using `strtol`, not preprocess.

**Pull request merged**
