### PR TITLE
Add additional debugging flags to drone GCC ASAN

### PR DESCRIPTION
**Pull request by mborland**
Drone log from PR #209 shows asan failure without any debug information or stacktrace.

### CODE REVIEW

**Comment by pdimov** [comment]
Both of these options should already be present. `-g` is supplied by `<debug-symbols>on`:

https://github.com/bfgroup/b2/blob/3c0f5630157c3db1025b54c2f6da25cf234b8e20/src/tools/gcc.jam#L678

and `-fno-omit-frame-pointer` is supplied by `<address-sanitizer>norecover`:

https://github.com/bfgroup/b2/blob/3c0f5630157c3db1025b54c2f6da25cf234b8e20/src/tools/gcc.jam#L695

The features, in turn, are supplied by drone.sh when ASAN is set:

https://github.com/boostorg/charconv/blob/9db7af735e435132d4849ad02a08eb7579103601/.drone/drone.sh#L28

**Comment by mborland** [comment]
Thanks as always @pdimov. I was hoping to get more since these failures seem extremely odd like limits_link_test having a seg fault on Drone while the fuzzers on GHA are fine. I'll try adding the same platform ASAN to GHA.

**Comment by pdimov** [comment]
The failures in #209 are a bit weird because (a) everything fails and (b) the push Drone job (which should be testing the same thing) succceeds.

**Comment by mborland** [comment]
> The failures in #209 are a bit weird because (a) everything fails and (b) the push Drone job (which should be testing the same thing) succceeds.

Yeah the ASAN GCC-12 runs fine on GHA. @sdarwin could this possibly be related to the image changes you made on Drone yesterday? The [push job](https://drone.cpp.al/boostorg/charconv/929) ran 4 days ago.

**Comment by mborland** [comment]
I'm seeing the odd segmentation faults in decimal as well: https://drone.cpp.al/cppalliance/decimal/1092/40/2. Many of these test are purely math operations.

**Comment by sdarwin** [comment]
PR 211 succeeded in Drone

**Pull request closed without merging**
