### PR TITLE
Conditionally link quadmath

### LINKED ISSUE #130: CMake targets don't link to quadmath
I'm encountering build errors because of undefined symbols when using CMake. It looks like `Boost::charconv` is failing to state the dependency.

* It occurs only when using the floating-point conversion functions.
* It happens when consuming the library from another library, via the superproject (I found this by having my MySQL test executables link to charconv). It also happens when creating a Boost distribution using CMake, and then consuming it via `find_package`. It doesn't happen when consuming the Boost CMake modules generated by b2.
* I'm seeing the errors under Ubuntu 22.04 and gcc-11. It happens under both Debug and Release, and with C++11 and C++20.
* Adding a `target_link_libraries(... quadmath)` such that `-lquadmath` is added to the link command line fixes the issue.

Full repro:

```
cd $BOOST_ROOT
mkdir -p __build && cd __build
cmake -DBOOST_INCLUDE_LIBRARIES=charconv -DCMAKE_INSTALL_PREFIX=/tmp/repro/    ..
make -j8 install
cd ~/repro-consumer
mkdir __build && cd __build
cmake -DCMAKE_PREFIX_PATH=/tmp/repro/ ..
make
```

File `~/repro-consumer/main.cpp`:

```
#include <boost/charconv/from_chars.hpp>

int main() {
  auto str = "42.0";
  float val = 0;
  boost::charconv::from_chars(str, str + 2, val);
}
```

File `~/repro-consumer/CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.12.0)
project(boost_mysql_example LANGUAGES CXX)

find_package(Boost REQUIRED COMPONENTS charconv)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE Boost::charconv)
```

### PR DESCRIPTION
**Pull request by mborland**
Closes: #130

### CODE REVIEW

**Comment by anarthal** [comment]
I've attempted this but it still fails. See https://drone.cpp.al/boostorg/mysql/484/2/3.

`find_library` is failing to detect `quadmath` support. From what I've seen in my system, `quadmath` doesn't seem to be located in the standard search paths (probably because it's an "internal" gcc library?).

From a quick search and inspecting your Jamfiles, I'd suggest to use the same approach in cmake. See https://github.com/sunqm/qcint/blob/master/cmake/FindQUADMATH.cmake for a possibility.

To locally reproduce the build environment I referenced above, I suggest you to use Docker. This build is using the image `ghcr.io/anarthal-containers/build-clang14`. `docker run -it ghcr.io/anarthal-containers/build-clang14` can do it.

**Comment by pdimov** [comment]
Is this the correct logic? Shouldn't Quadmath be linked only when needed, not whenever it's present?

**Comment by mborland** [comment]
> Is this the correct logic? Shouldn't Quadmath be linked only when needed, not whenever it's present?

I thought so since CMake defaults to building with "gnu++". It's nearly the same issue that we ran into with the CMake testing suite.

**Comment by pdimov** [comment]
Never mind, I see that Jamfile does the same thing. I suppose `config/has_float128.cpp` can be reused on the CMake side as well.

**Comment by mborland** [comment]
> I've attempted this but it still fails. See https://drone.cpp.al/boostorg/mysql/484/2/3.
> 
> `find_library` is failing to detect `quadmath` support. From what I've seen in my system, `quadmath` doesn't seem to be located in the standard search paths (probably because it's an "internal" gcc library?).
> 
> From a quick search and inspecting your Jamfiles, I'd suggest to use the same approach in cmake. See https://github.com/sunqm/qcint/blob/master/cmake/FindQUADMATH.cmake for a possibility.
> 
> To locally reproduce the build environment I referenced above, I suggest you to use Docker. This build is using the image `ghcr.io/anarthal-containers/build-clang14`. `docker run -it ghcr.io/anarthal-containers/build-clang14` can do it.

Using this docker image I am able to compile and run your demo program with latest commit pulled in. In the cmake testing setting cmake extensions to off didn't work either so a macro was added to compile without any of the quadmath support. That macro is now defined if quadmath is not found, and also gives the user the option if they want. Seems to also work fine with the cmake based testing in the CI here. @anarthal let me know if your CI goes green with this now.

**Comment by anarthal** [comment]
It does build. However, it seems to be always detecting that `libquadmath` is not there. From my tests, it looks like you could define BOOST_CHARCONV_NO_QUADMATH to 1 unconditionally and yield the same results.

I don't need any __float128 support, so it's up to you if you want to resolve this like this or not.

**Pull request merged**
